version: '3'
services:
  postgresql:
    image: chefdemo/postgresql:stable
    environment:
      HAB_POSTGRESQL: |
        [superuser]
        name = 'hab'
        password = 'chefrocks'
    volumes:
      - postgresql-data:/hab/svc/postgresql/data

  elasticsearch:
    image: chefdemo/elasticsearch:stable
    command: --peer postgresql
    depends_on:
      - postgresql
    links:
      - postgresql

  bookshelf:
    image: $HAB_ORIGIN/bookshelf
    depends_on:
      - postgresql
    links:
      - postgresql
    environment:
      - FOO=bar
    command: --peer postgresql
      --bind database:postgresql.default

  oc_bifrost:
    image: $HAB_ORIGIN/oc_bifrost
    depends_on:
      - postgresql
    links:
      - postgresql
    environment:
      - FOO=bar
    command: --peer postgresql
      --bind database:postgresql.default

  oc_erchef:
    image: $HAB_ORIGIN/oc_erchef
    depends_on:
      - elasticsearch
      - oc_bifrost
      - postgresql
    links:
      - elasticsearch
      - oc_bifrost
      - postgresql
    environment:
      - FOO=bar
    command: --peer postgresql
      --bind oc_bifrost:oc_bifrost.default
      --bind database:postgresql.default
      --bind elasticsearch:elasticsearch.default

  chef-server-nginx:
    image: $HAB_ORIGIN/chef-server-nginx
    depends_on:
      - oc_erchef
      - oc_bifrost
      - bookshelf
      - postgresql
    links:
      - oc_erchef
      - oc_bifrost
      - bookshelf
      - elasticsearch
      - postgresql
    environment:
      - FOO=bar
    command: --peer postgresql
      --bind oc_erchef:oc_erchef.default
      --bind oc_bifrost:oc_bifrost.default
      --bind bookshelf:bookshelf.default
      --bind elasticsearch:elasticsearch.default
      
volumes:
  postgresql-data:
